spring:
  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:15068/railway
    username: postgres
    password: UlvkeoQAbPAXWVgbiITEYJBOKKVmnivH
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
